package com.arriendosreal.webapp.entities;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedStoredProcedureQuery;
import javax.persistence.ParameterMode;
import javax.persistence.StoredProcedureParameter;
import javax.persistence.Table;

/**
 * Acompanantes generated by hbm2java
 */
@Entity
@Table(name = "ACOMPANANTES")
@NamedStoredProcedureQuery(name = "Acompanantes.createAcompanante", procedureName = "SP_CREAR_ACOMPANANTE", parameters = {
        @StoredProcedureParameter(mode = ParameterMode.IN, name = "in_rut", type = String.class),
        @StoredProcedureParameter(mode = ParameterMode.IN, name = "in_nombre", type = String.class),
        @StoredProcedureParameter(mode = ParameterMode.IN, name = "in_apellido_pat", type = String.class),
        @StoredProcedureParameter(mode = ParameterMode.IN, name = "in_apellido_mat", type = String.class),
        @StoredProcedureParameter(mode = ParameterMode.IN, name = "in_Reservas_id_reserva", type = Integer.class),
        @StoredProcedureParameter(mode = ParameterMode.OUT, name = "out_resultado", type = Integer.class) })

@NamedStoredProcedureQuery(name = "Acompanantes.updateAcompanante", procedureName = "SP_UPD_ACOMPANANTE", parameters = {
        @StoredProcedureParameter(mode = ParameterMode.IN, name = "in_id_acompanante", type = Integer.class),
        @StoredProcedureParameter(mode = ParameterMode.IN, name = "in_rut", type = String.class),
        @StoredProcedureParameter(mode = ParameterMode.IN, name = "in_nombre", type = String.class),
        @StoredProcedureParameter(mode = ParameterMode.IN, name = "in_apellido_pat", type = String.class),
        @StoredProcedureParameter(mode = ParameterMode.IN, name = "in_apellido_mat", type = String.class),
        @StoredProcedureParameter(mode = ParameterMode.IN, name = "in_Reservas_id_reserva", type = Integer.class),
        @StoredProcedureParameter(mode = ParameterMode.OUT, name = "out_resultado", type = Integer.class) })

@NamedStoredProcedureQuery(name = "Acompanantes.deleteAcompanante", procedureName = "SP_DEL_ACOMPANANTE", parameters = {
        @StoredProcedureParameter(mode = ParameterMode.IN, name = "in_id_acompanante", type = Integer.class),
        @StoredProcedureParameter(mode = ParameterMode.OUT, name = "out_estado", type = Integer.class) })

public class Acompanantes implements java.io.Serializable {

    private BigDecimal idAcompanante;
    private Reservas reservas;
    private String rut;
    private String nombre;
    private String apellidoPat;
    private String apellidoMat;

    public Acompanantes() {
    }

    public Acompanantes(BigDecimal idAcompanante, Reservas reservas) {
        this.idAcompanante = idAcompanante;
        this.reservas = reservas;
    }

    public Acompanantes(BigDecimal idAcompanante, Reservas reservas, String rut, String nombre, String apellidoPat,
            String apellidoMat) {
        this.idAcompanante = idAcompanante;
        this.reservas = reservas;
        this.rut = rut;
        this.nombre = nombre;
        this.apellidoPat = apellidoPat;
        this.apellidoMat = apellidoMat;
    }

    @Id

    @Column(name = "ID_ACOMPANANTE", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getIdAcompanante() {
        return this.idAcompanante;
    }

    public void setIdAcompanante(BigDecimal idAcompanante) {
        this.idAcompanante = idAcompanante;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RESERVAS_ID_RESERVA", nullable = false)
    public Reservas getReservas() {
        return this.reservas;
    }

    public void setReservas(Reservas reservas) {
        this.reservas = reservas;
    }

    @Column(name = "RUT", length = 50)
    public String getRut() {
        return this.rut;
    }

    public void setRut(String rut) {
        this.rut = rut;
    }

    @Column(name = "NOMBRE", length = 50)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "APELLIDO_PAT", length = 50)
    public String getApellidoPat() {
        return this.apellidoPat;
    }

    public void setApellidoPat(String apellidoPat) {
        this.apellidoPat = apellidoPat;
    }

    @Column(name = "APELLIDO_MAT", length = 50)
    public String getApellidoMat() {
        return this.apellidoMat;
    }

    public void setApellidoMat(String apellidoMat) {
        this.apellidoMat = apellidoMat;
    }

}
