package com.arriendosreal.webapp.entities;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Resumen generated by hbm2java
 */
@Entity
@Table(name = "RESUMEN")
public class Resumen implements java.io.Serializable {

    private BigDecimal idResumen;
    private BigDecimal ingreso;
    private BigDecimal egreso;
    private Date fecha;

    public Resumen() {
    }

    public Resumen(BigDecimal idResumen) {
        this.idResumen = idResumen;
    }

    public Resumen(BigDecimal idResumen, BigDecimal ingreso, BigDecimal egreso, Date fecha) {
        this.idResumen = idResumen;
        this.ingreso = ingreso;
        this.egreso = egreso;
        this.fecha = fecha;
    }

    @Id

    @Column(name = "ID_RESUMEN", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getIdResumen() {
        return this.idResumen;
    }

    public void setIdResumen(BigDecimal idResumen) {
        this.idResumen = idResumen;
    }

    @Column(name = "INGRESO", precision = 22, scale = 0)
    public BigDecimal getIngreso() {
        return this.ingreso;
    }

    public void setIngreso(BigDecimal ingreso) {
        this.ingreso = ingreso;
    }

    @Column(name = "EGRESO", precision = 22, scale = 0)
    public BigDecimal getEgreso() {
        return this.egreso;
    }

    public void setEgreso(BigDecimal egreso) {
        this.egreso = egreso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA", length = 7)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

}
