package com.arriendosreal.webapp.entities;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedStoredProcedureQuery;
import javax.persistence.ParameterMode;
import javax.persistence.StoredProcedureParameter;
import javax.persistence.Table;

/**
 * TiposServicio generated by hbm2java
 */
@Entity
@Table(name = "TIPOS_SERVICIO")

@NamedStoredProcedureQuery(name = "TiposServicio.createTipoServicio", procedureName = "SP_CREAR_TIPO_SERVICIO", parameters = {
        @StoredProcedureParameter(mode = ParameterMode.IN, name = "in_descripcion", type = String.class),
        @StoredProcedureParameter(mode = ParameterMode.OUT, name = "out_resultado", type = Integer.class)})

@NamedStoredProcedureQuery(name = "TiposServicio.updateTipoServicio", procedureName = "SP_UPD_TIPO_SERVICIO", parameters = {
        @StoredProcedureParameter(mode = ParameterMode.IN, name = "in_id_tipo", type = Integer.class),
        @StoredProcedureParameter(mode = ParameterMode.IN, name = "in_descripcion", type = String.class),
        @StoredProcedureParameter(mode = ParameterMode.OUT, name = "out_resultado", type = Integer.class)})

@NamedStoredProcedureQuery(name = "TiposServicio.deleteTipoServicio", procedureName = "SP_DEL_TIPO_SERVICIO", parameters = {
        @StoredProcedureParameter(mode = ParameterMode.IN, name = "in_id_tipo", type = Integer.class),
        @StoredProcedureParameter(mode = ParameterMode.OUT, name = "out_estado", type = Integer.class)})

public class TiposServicio implements java.io.Serializable {

    private BigDecimal idTipo;
    private String descripcion;

    public TiposServicio() {
    }

    public TiposServicio(BigDecimal idTipo) {
        this.idTipo = idTipo;
    }
    
    public TiposServicio(BigDecimal idTipo, String descripcion) {
        this.idTipo = idTipo;
        this.descripcion = descripcion;
    }

    @Id

    @Column(name = "ID_TIPO", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getIdTipo() {
        return this.idTipo;
    }

    public void setIdTipo(BigDecimal idTipo) {
        this.idTipo = idTipo;
    }

    @Column(name = "DESCRIPCION", length = 250)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

}
