package com.arriendosreal.webapp.entities;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TiposServicio generated by hbm2java
 */
@Entity
@Table(name = "TIPOS_SERVICIO")
public class TiposServicio implements java.io.Serializable {

    private BigDecimal idTipo;
    private String descripcion;
    private Set<Servicios> servicioses = new HashSet<Servicios>(0);

    public TiposServicio() {
    }

    public TiposServicio(BigDecimal idTipo) {
        this.idTipo = idTipo;
    }

    public TiposServicio(BigDecimal idTipo, String descripcion, Set<Servicios> servicioses) {
        this.idTipo = idTipo;
        this.descripcion = descripcion;
        this.servicioses = servicioses;
    }

    @Id

    @Column(name = "ID_TIPO", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getIdTipo() {
        return this.idTipo;
    }

    public void setIdTipo(BigDecimal idTipo) {
        this.idTipo = idTipo;
    }

    @Column(name = "DESCRIPCION", length = 250)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tiposServicio")
    public Set<Servicios> getServicioses() {
        return this.servicioses;
    }

    public void setServicioses(Set<Servicios> servicioses) {
        this.servicioses = servicioses;
    }

}
