package com.arriendosreal.webapp.entities;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedStoredProcedureQuery;
import javax.persistence.StoredProcedureParameter;
import javax.persistence.ParameterMode;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "USERS")
@NamedStoredProcedureQuery(name = "USERS.sp_i_users", 
procedureName = "sp_i_users", parameters = {
  @StoredProcedureParameter(mode = ParameterMode.IN, name = "model_in", type = String.class),
  @StoredProcedureParameter(mode = ParameterMode.IN, name = "model_in", type = String.class),
  @StoredProcedureParameter(mode = ParameterMode.IN, name = "model_in", type = String.class),
  @StoredProcedureParameter(mode = ParameterMode.IN, name = "model_in", type = String.class),
  @StoredProcedureParameter(mode = ParameterMode.OUT, name = "count_out", type = Integer.class)})

public class Users implements java.io.Serializable {

	private BigDecimal userId;
	private Profiles profiles;
	private String username;
	private String email;
	private String password;
	private Set<Personas> personases = new HashSet<Personas>(0);

	public Users() {
	}

	public Users(BigDecimal userId, Profiles profiles, String username, String email, String password) {
		this.userId = userId;
		this.profiles = profiles;
		this.username = username;
		this.email = email;
		this.password = password;
	}

	public Users(BigDecimal userId, Profiles profiles, String username, String email, String password,
			Set<Personas> personases) {
		this.userId = userId;
		this.profiles = profiles;
		this.username = username;
		this.email = email;
		this.password = password;
		this.personases = personases;
	}

	@Id

	@Column(name = "USER_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getUserId() {
		return this.userId;
	}

	public void setUserId(BigDecimal userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROFILES_PROFILE_ID", nullable = false)
	public Profiles getProfiles() {
		return this.profiles;
	}

	public void setProfiles(Profiles profiles) {
		this.profiles = profiles;
	}

	@Column(name = "USERNAME", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "EMAIL", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PASSWORD", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Personas> getPersonases() {
		return this.personases;
	}

	public void setPersonases(Set<Personas> personases) {
		this.personases = personases;
	}

}
